INSERT INTO Raza (nombre)
VALUES ('Labrador')
INSERT INTO Raza (nombre)
VALUES ('Golden Retriever')
INSERT INTO Raza (nombre)
VALUES ('Bulldog Frances')
INSERT INTO Raza (nombre)
VALUES ('Bulldog Ingles')
INSERT INTO Raza (nombre)
VALUES ('Husky Siberiano')
INSERT INTO Raza (nombre)
VALUES ('Beagle')
INSERT INTO Raza (nombre)
VALUES ('Dachshund')
INSERT INTO Raza (nombre)
VALUES ('Dogo')
INSERT INTO Raza (nombre)
VALUES ('Pitbull')
INSERT INTO Raza (nombre)
VALUES ('Doberman')
INSERT INTO Raza (nombre)
VALUES ('Chihuahua')
INSERT INTO Raza (nombre)
VALUES ('Caniche')
INSERT INTO Raza (nombre)
VALUES ('Rottweiler')
INSERT INTO Raza (nombre)
VALUES ('Cocker Spaniel')
INSERT INTO Raza (nombre)
VALUES ('Schnauzer')
INSERT INTO Raza (nombre)
VALUES ('Dalmata')
INSERT INTO Raza (nombre)
VALUES ('Corgi')
INSERT INTO Raza (nombre)
VALUES ('Mestizo')
INSERT INTO Raza (nombre)
VALUES ('Pastor Australiano')
INSERT INTO Raza (nombre)
VALUES ('Pastor Aleman')
INSERT INTO Raza (nombre)
VALUES ('Siames')
INSERT INTO Raza (nombre)
VALUES ('British Shorthair') 
INSERT INTO Raza (nombre)
VALUES ('Maine Coon')
INSERT INTO Raza (nombre)
VALUES ('Persa')
INSERT INTO Raza (nombre)
VALUES ('Ragdoll')
INSERT INTO Raza (nombre)
VALUES ('Esfinge')
INSERT INTO Raza (nombre)
VALUES ('Abisinio')
INSERT INTO Raza (nombre)
VALUES ('Burnes')
INSERT INTO Raza (nombre)
VALUES ('Bombay')
INSERT INTO Raza (nombre)
VALUES ('Birmano')
INSERT INTO Raza (nombre)
VALUES ('Siberiano')
INSERT INTO Raza (nombre)
VALUES ('Munchkin')
INSERT INTO Raza (nombre)
VALUES ('Curl Americano')
INSERT INTO Raza (nombre)
VALUES ('Bobtail Americano')
INSERT INTO Raza (nombre)
VALUES ('Somali')
INSERT INTO Raza (nombre)
VALUES ('Korat')
INSERT INTO Raza (nombre)
VALUES ('Egipcio')
INSERT INTO Raza (nombre)
VALUES ('Otro')
